name: Tox pytest all python versions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip" #Note that pip is for the tox level. Poetry is still used for installing the specific environments (tox.ini)

      - name: Install nox
        run: pip install nox

      - name: Run nox
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: nox

      - name: Report coverage
        run: |
          bash <(curl -s https://codecov.io/bash)
